# Generated by Django 4.2.2 on 2023-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
